name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - csv
  - datetime
  - json
  - os
  - statistics
  - pandas
  - time
  - matplotlib
  - random
  - intertools
  - glob
  - seaborn
  - requests
